### ISSUE TITLE
Bug: watch command not synchronizing correctly

### ISSUE THREAD

**Issue by gordom6** [tetherless-world/twks#106]
Henrique: I caught a TWKS bug at least on the version that I am using. When we insert some policies through the editor, although the watch command triggers with the new nanopub, the new policy doesn’t become available during reasoning time. If I restart TWKS server and watch command, then everything works. We don’t need to worry about that for the demo tomorrow

**Comment by hansidm** [comment]
Here's the watch command
`java -jar twks-cli-cuent.jar -Dtwks.serverBaseUrl=http://localhost:8082 watch-nanopublications --dialect WHYIS /data/nanopublications/`
