### ISSUE TITLE
Documentation mentions unsupported `-T` flag

### ISSUE THREAD

**Issue by Aaron1011** [tetherless-world/twks#131]
The document for `script/cli` currently mentions a `-T` flag: https://twks.readthedocs.io/en/latest/docker.html#running-the-twks-command-line-interface-with-docker.

However, `script/cli` doesn't seem to accept this flag.

**Comment by gordom6** [comment]
-T is a Docker flag. This was a holdover when there was a `docker` command line instead of the convenience `script/cli`. I've updated this in the course of fixing #134. Will close this and ask for review tehre.
