### ISSUE TITLE
`twks-java` image is not built by `script/server`

### ISSUE THREAD

**Issue by Aaron1011** [tetherless-world/twks#132]
The documentation [currently states](https://twks.readthedocs.io/en/latest/docker.html#running-the-twks-server-in-docker) that running `script/server` is sufficient to start the TWKS server. However, this relies on having the `twks-java` already built. Attempting to run `script/server` from a fresh install (no pre-existing Docker images) gives the following error:

```
Building twks-server
Step 1/17 : FROM twks-java as build-java
ERROR: Service 'twks-server' failed to build: pull access denied for twks-java, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

For `script/server` to work, it's necessary to manually run `docker-compose build` from `docker/compose/build`. This appears to make the required images available so that `script/server` can succeed.

It would be useful if it was only necessary to run `script/server` to run the TWKS server on a new machine.

**Comment by gordom6** [comment]
I updated the documentation to explain how to build the images, and also added a `docker/script/pull` to download images instead of building them.

**Comment by gordom6** [comment]
I've merged all that to master, it will push to readthedocs shortly. Please join #twks and #twks-ci on TWC Slack to follow development if you're going to be working on this.

**Comment by gordom6** [comment]
Please close this issue once you can try the updated documentation.

**Comment by Aaron1011** [comment]
The updated documentation works for me - thanks!
