### ISSUE TITLE
Using `script/cli` creates a new Docker container per invocation

### ISSUE THREAD

**Issue by Aaron1011** [tetherless-world/twks#133]
Running `script/cli` invokes `docker-compose run`, which creates a new container. This causes a new Docker container to be created every single time `script/cli` is invoked, which causes many unused containers to accumulate on the system.

I think it would a good idea for `script/cli` to either re-use the same Docker container across multiple invocations, or to automatically clear out old containers (since there doesn't appear to be any state shared between invocations).

**Comment by gordom6** [comment]
Added --rm to the run command to remove the container after it exits.

**Comment by gordom6** [comment]
Please close this issue if it works for you.
