### ISSUE TITLE
TWKS CLI attempts to connect to `localhost:8080` by default

### ISSUE THREAD

**Issue by Aaron1011** [tetherless-world/twks#134]
When `script/cli` is used, the TWKS client will never be able to connect to `localhost:8080`, since the client is running in its own docker container. I'm not certain how to give that container access to port `8080` on the server container, but it would be useful if `script/cli` overrode the default server URL (or prompted the user for it).

**Comment by gordom6** [comment]
I changed `script/cli` to connect to `twks-server` by default and changed the `script/server` underlying composing file to be on the same network as the CLI. I also updated the documentation with the correct command line.

I've merged all of this into master.

Please test and close this issue if it works for you.
